#! /bin/sh

echo "save_quicklook $1" 
echo "save_data: $2"
echo "save_netCDF: $3"
echo "save_catalog: $4"
echo "node: $5"
# get yesterday date and year to feed into Matlab
daystr=`date +%y%m%d -d "1 day ago"`
year=`date +%Y -d "1 day ago"`
# Outputting date and year for user to see 
echo "daystr = $daystr"
echo "year = $year"
# Outputting the DIAL system for user to see
node=\'$5\'
echo "node = ${node}"
# set the Matlab command
matcmd="addpath $HOME/processing/MatlabV2; WVDIALProcessingV01_01_function(${daystr},$1,$2,$3,$4,${node}); exit"
# file, save_quicklook, save_data, save_netCDF, save_catalog
cmd="/opt/local/bin/matlab -nodisplay -nosplash -r \"$matcmd\""
echo "cmd = $cmd"
# run the command
eval $cmd

