#! /bin/sh

echo "Current Time: `date +%Y%m%d-%H%M%S`"
echo "System: $1" 
echo "Logging: $2"
echo "Email: $3"
echo "Targets: $4"
# get current date and year to feed into Matlab
daystr=\'`date -u +%Y%m%d`\'
echo "daystr = $daystr"
node=\'$1\'
logging=\'$2\'
email=\$3
targets=$4
# set the Matlab command
if [[ ${node} == "'mpd_06'" ]]; then
process=false
else
process=true
fi

#echo $process

matcmd="cd('/home/rsfdata/git/WVD-MatlabProcessing'); [~]=RunLoader(${daystr},${node},${logging},true,$process,false,false,$email,{$targets}); exit"
# file, save_quicklook, save_data, save_netCDF, save_catalog
cmd="/opt/local/MATLAB/R2023b/bin/matlab -nodisplay -nosplash -r \"$matcmd\""
echo "cmd = $cmd"
# run the command
eval $cmd
