#! /bin/sh

echo "Current Time: `date +%Y%m%d-%H%M%S`"
echo "System: $1" 
echo "Logging: $2"
# get current date and year to feed into Matlab
daystr=\'`date -u +%Y%m%d`\'
echo "daystr = $daystr"
node=\'$1\'
logging=\'$2\'
# set the Matlab command
matcmd="cd('/home/rsfdata/git/WVD-MatlabProcessing'); [~]=RunLoader(${daystr},${node},${logging},true,true,false,false); exit"
# file, save_quicklook, save_data, save_netCDF, save_catalog
cmd="/opt/local/bin/matlab -nodisplay -nosplash -r \"$matcmd\""
echo "cmd = $cmd"
# run the command
eval $cmd
