#! /bin/sh

echo "Current Time: `date +%Y%m%d-%H%M%S`"
echo "System: $1" 
echo "Logging: $2"
# get yesterday's date to feed into Matlab
daystr=\'`date +%Y%m%d -d "1 day ago"`\'
echo "daystr = $daystr"
node=\'$1\'
logging=\'$2\'
# set the Matlab command
matcmd="cd('/home/rsfdata/git/WVD-MatlabProcessing'); [~]=RunLoader(${daystr},${node},${logging},false,true,true,true); exit"
# file, save_quicklook, save_data, save_netCDF, save_catalog
cmd="/opt/local/MATLAB/R2023a/bin/matlab -nodisplay -nosplash -r \"$matcmd\""
echo "cmd = $cmd"
# run the command
eval $cmd
